version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - bash build.sh
  post_build:
    commands:
      - bash post_build.sh
artifacts:
  files:
    - 'build/Dockerrun.aws.json'
  discard-paths: yes
  name: $CODEBUILD_SOURCE_VERSION-codebuild 