version: "3.1"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: lol
  redis:
    image: redis
  api:
    build:
      context: ../api
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules # tell docker not to overwrite node modules
      - ../api:/app # mount source folder
    environment:
      PG_DATABASE: postgres
      PG_HOST: postgres
      PG_PASSWORD: lol
      PG_PORT: "5432"
      PG_USER: postgres
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      API_PORT: "5000"
  worker:
    build:
      context: ../worker
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules # tell docker not to overwrite node modules
      - ../worker:/app # mount source folder
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
  client:
    depends_on: ["worker"]
    build:
      context: ../client
      dockerfile: dev.Dockerfile
    volumes:
      - /app/node_modules # tell docker not to overwrite node modules
      - ../client:/app # mount source folder
  router:
    restart: always
    build:
      context: ../router
      dockerfile: dev.Dockerfile
    environment:
      CLIENT_PORT: "3000"
      API_PORT: "5000"
    ports:
      - "3050:80"
